language: cpp

env:
  matrix:
    # gcc default build
    - USE_CC=gcc     USE_CXX=g++
    # clang default build
    - USE_CC=clang   USE_CXX=clang++

    # build with older gcc
    - USE_CC=gcc-4.6 USE_CXX=g++-4.6

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - if [ "$USE_CXX" == "g++-4.6" ]; then sudo apt-get install g++-4.6; fi

# before_script:
#   - export CC="$USE_CC" CXX="$USE_CXX"
#   - mkdir build && cd build && ../configure --enable-speedtest

script:
  - cmake. 
  - make
  - ./stx_btree